/home/sathap1/newriver_local/venvs/tfgpu/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
2018-05-18 17:55:28.294805: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-05-18 17:55:28.537512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:02:00.0
totalMemory: 11.91GiB freeMemory: 11.62GiB
2018-05-18 17:55:28.537550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:02:00.0, compute capability: 6.0)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/sathap1/newriver_local/venvs/tfgpu/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/sathap1/newriver_local/venvs/tfgpu/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sathap1/newriver_local/venvs/tfgpu/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/utils/data_utils.py", line 588, in data_generator_task
    generator_output = next(self._generator)
  File "/home/sathap1/workspace/bioFunctionPrediction/src/utils/dataloader.py", line 342, in __next__
    raise StopIteration
StopIteration

Traceback (most recent call last):
  File "/home/sathap1/workspace/bioFunctionPrediction/src//keras_deepgorun.py", line 166, in <module>
    tf.app.run(main)
  File "/home/sathap1/newriver_local/venvs/tfgpu/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/sathap1/workspace/bioFunctionPrediction/src//keras_deepgorun.py", line 150, in main
    callbacks=[checkpointer, earlystopper])
  File "/home/sathap1/newriver_local/venvs/tfgpu/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 2048, in fit_generator
    generator_output = next(output_generator)
StopIteration

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True


Usage:
 kill [options] <pid|name> [...]

Options:
 -a, --all              do not restrict the name-to-pid conversion to processes
                        with the same uid as the present process
 -s, --signal <sig>     send specified signal
 -q, --queue <sig>      use sigqueue(2) rather than kill(2)
 -p, --pid              print pids without signaling them
 -l, --list [=<signal>] list signal names, or convert one to a name
 -L, --table            list signal names and numbers

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).

Usage:
 kill [options] <pid|name> [...]

Options:
 -a, --all              do not restrict the name-to-pid conversion to processes
                        with the same uid as the present process
 -s, --signal <sig>     send specified signal
 -q, --queue <sig>      use sigqueue(2) rather than kill(2)
 -p, --pid              print pids without signaling them
 -l, --list [=<signal>] list signal names, or convert one to a name
 -L, --table            list signal names and numbers

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).
